// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"
//        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
//        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
    }
}

//apply plugin: 'com.jfrog.bintray'

allprojects {
    repositories {
        jcenter()
        maven {
            url  "https://dl.bintray.com/laobie/maven"
        }
        mavenCentral()
        google()
    }
//    configurations.configureEach {
//        resolutionStrategy {
//            force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
//            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
//            force 'androidx.appcompat:appcompat:1.7.0'
//            force 'androidx.legacy:legacy-support-v4:1.0.0'
//        }
//    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
